import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Layout pageTitle="Inicio" metaDescription="Hola" currentRoute="a">
      <div className="pt-0 ">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1>HELLO! Work in progress</h1>
          <p>Aaaaaaaaaa</p>
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </Layout>
  );
};

export default Home;
